services:
  app:
    build:
      context: ./
      dockerfile: ./../Dockerfile
      args:
        SCRIPT_DIR: "ingestion"
    environment:
      DOCKERIZED: "absolutely"
      LOCALSTACK_URL: "http://localstack:4566"
      S3_BUCKET: "fake"
      DB_CONNECTION: "mongodb://mongo:27017"
      DATABASE_NAME: "ebola"
      GH_COLLECTION: "gh"
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
  localstack:
    image: localstack/localstack
    environment:
      AWS_ACCESS_KEY_ID: "fake"
      AWS_SECRET_ACCESS_KEY: "fake"
      SERVICES: "s3"
      DOCKER_HOST: "unix:///var/run/docker.sock"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
  mongo:
    image: mongo:5.0.12
    restart: always
    init: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "ebola"
