name: Test GSheets to S3/DB script

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/gh_data_update_tests.yml'
      - 'scripts/ingestion/*.py'
      - 'scripts/ingestion/pyproject.toml'
      - 'scripts/ingestion/poetry.lock'
      - 'scripts/Dockerfile-test'
  pull_request:
    paths:
      - '.github/workflows/gh_data_update_tests.yml'
      - 'scripts/ingestion/*.py'
      - 'scripts/ingestion/pyproject.toml'
      - 'scripts/ingestion/poetry.lock'
      - 'scripts/Dockerfile-test'


jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: cd scripts/ingestion && ./test_stack.sh